import type { Pizzaiolo } from "./types";

export const PIZZAIOLI: Pizzaiolo[] = [
  {
    id: "pino-prestanizzi",
    name: "Pino Prestanizzi",
    style: "Traditional Neapolitan",
    hydration: 0.60,
    salt: 0.030,
    yeast: 0.0050,
    fermentationMin: 8,
    fermentationMax: 24,
    sauce: { tomatoType: "San Marzano DOP", saltPercent: 0.008, oliveOilPercent: 0, basil: false, notesPerPizza: 100 },
    color: "#FF6B35",
    flourW: "W280–300",
    hydrationRange: "58–62%",
    saltRange: "2.8–3.0%",
    yeastRange: "0.3–0.8%",
    fermentationRange: "8–24 hrs",
    mixing: "Direct",
    characteristics: "Easy to handle, less sticky, classic Naples style with moderate oven spring",
    mainFocus: "Traditional Naples techniques, lower hydration, consistency.",
    recipe1000g: { water: "600g", salt: "30g", yeast: "5g IDY" },
    fermentationApproach: "Traditional direct dough",
    bulkTime: "2–4 hrs",
    ballTime: "6–18 hrs",
    totalTime: "8–24 hrs",
    tempPreference: "Mostly room temp",
    saucePreference: "Crushed San Marzano Tomato with salt only",
    philosophy: "Simplicity and consistency.",
    saucePhilosophy: "Traditional Naples minimalism; crushed tomatoes and salt only.",
    sauceRecipe1000g: { tomatoes: "1000g", salt: "10–12g", oliveOil: "None", basil: "Optional", other: "None" },
    technique: {
      level: "Classical Round High-Heat Adapt",
      stretching: "Rapid, confident palm and finger work. Push down flatly from the center outward, spinning the dough ball continuously to keep a consistent circular thickness.",
      notes: [
        { title: "Sauce Control", detail: "Spread tomato sauce evenly using the flat bottom of a ladle in fluid circular motions, right up to the boundary of the crust border." },
        { title: "Bake Management", detail: "On higher-hydration variants (~70%), use the turning peel to shift the pizza across different zones of the stone floor to manage bottom crispiness." },
      ],
      videos: [
        { category: "general", title: "How to make pizza at home (full build)", url: "https://www.youtube.com/watch?v=CGWfHHn6dL8" },
        { category: "stretching", title: "How to stretch pizza correctly (no rolling pin)", url: "https://www.youtube.com/watch?v=AU8HzRuIEwM" },
        { category: "fermentation", title: "3h, 12h, and 24h fermentation", url: "https://www.youtube.com/watch?v=rG444gOSIr4&t=1s" },
      ],
    },
  },
  {
    id: "ciro-salvo",
    name: "Ciro Salvo",
    style: "Modern Neapolitan",
    hydration: 0.72,
    salt: 0.028,
    yeast: 0.0010,
    fermentationMin: 24,
    fermentationMax: 48,
    sauce: { tomatoType: "San Marzano + Pomodorino del Piennolo", saltPercent: 0.004, oliveOilPercent: 0, basil: false, notesPerPizza: 90 },
    color: "#D4A373",
    flourW: "W300–330",
    hydrationRange: "70–75%",
    saltRange: "2.7–3.0%",
    yeastRange: "0.05–0.15%",
    fermentationRange: "24–48 hrs",
    mixing: "Direct",
    characteristics: "Extremely light, airy cornicione, highly extensible dough",
    mainFocus: "Maximum lightness and digestibility through very high hydration.",
    recipe1000g: { water: "720g", salt: "28g", yeast: "1g fresh yeast" },
    fermentationApproach: "Long fermentation, minimal yeast",
    bulkTime: "12–24 hrs",
    ballTime: "12–24 hrs",
    totalTime: "24–48 hrs",
    tempPreference: "Cold + ambient",
    saucePreference: "Hand-crushed premium tomatoes, minimal seasoning",
    philosophy: "Maximum digestibility and lightness.",
    saucePhilosophy: "Tomatoes should taste like tomatoes; minimal additions.",
    sauceRecipe1000g: { tomatoes: "1000g", salt: "8–10g", oliveOil: "None", basil: "Optional", other: "None" },
    technique: {
      level: "Extreme Hydration Direct Process",
      stretching: "Hydration is exceptionally high, so the dough structure is delicate. Drop the ball into a heavy bed of semolina, lift carefully, then push from the inside outward with soft finger padding.",
      notes: [
        { title: "Strategy", detail: "Recognized as a “King of Dough” for pushing Neapolitan parameters into very high-hydration realms (73–75%) with long direct fermentation — resulting in an airy, meltingly soft, easily digestible crust." },
        { title: "Peel Speed", detail: "Dress and launch the pizza within ~30 seconds of it hitting any surface, or the high water content will form a bond and cause it to stick." },
      ],
      videos: [
        { category: "general", title: "Italia Squisita — 50 Kalò Neapolitan pizza recipe (full masterclass: dough → stretch → sauce → bake)", url: "https://www.youtube.com/watch?v=TBTa3n_0N-A" },
      ],
    },
  },
  {
    id: "mike-g",
    name: "Mike G",
    style: "Contemporary Neapolitan",
    hydration: 0.68,
    salt: 0.028,
    yeast: 0.0020,
    fermentationMin: 24,
    fermentationMax: 72,
    sauce: { tomatoType: "Bianco DiNapoli", saltPercent: 0.006, oliveOilPercent: 0, basil: false, notesPerPizza: 95 },
    color: "#4ADE80",
    flourW: "W300–330",
    hydrationRange: "65–70%",
    saltRange: "2.5–3.0%",
    yeastRange: "0.1–0.3%",
    fermentationRange: "24–72 hrs",
    mixing: "Direct/Biga",
    characteristics: "Balanced handling and openness",
    mainFocus: "Practical modern Neapolitan formulas for home and professional ovens.",
    recipe1000g: { water: "680g", salt: "28g", yeast: "2g IDY" },
    fermentationApproach: "Flexible direct method",
    bulkTime: "12–24 hrs",
    ballTime: "12–48 hrs",
    totalTime: "24–72 hrs",
    tempPreference: "Cold ferment",
    saucePreference: "Lightly seasoned crushed tomatoes",
    philosophy: "Practical, repeatable home and professional results.",
    saucePhilosophy: "Light seasoning with a touch of oil for home ovens.",
    sauceRecipe1000g: { tomatoes: "1000g", salt: "10g", oliveOil: "5–10g", basil: "Optional", other: "None" },
    technique: {
      level: "Peel-Built High-Hydration Slide",
      stretching: "At ~75% hydration the dough is soft and extensible. Lift it onto the backs of the knuckles and let gravity naturally widen it out into a large 14\" round.",
      notes: [
        { title: "Peel Assembly", detail: "Place the naked stretched dough directly onto a heavily floured placement peel first. Then work fast — top with sauce, cheese, and proteins in under 30 seconds before the wet dough can bond to the metal surface." },
      ],
      videos: [
        { category: "general", title: "Life by Mike G — A Master Class in Neapolitan Pizza Making (full breakdown: dough, fermentation, sauce, stretch)", url: "https://lifebymikeg.com/blogs/all/a-master-class-in-neapolitan-pizza-making-full-breakdown" },
        { category: "general", title: "Life by Mike G — pizza video", url: "https://www.youtube.com/watch?v=RCl1dU5TzXs" },
        { category: "general", title: "Making New York Pizza from 0", url: "https://www.youtube.com/watch?v=GI_JwhwRl_I" },
      ],
    },
  },
  {
    id: "eric-ayala",
    name: "Eric Ayala",
    style: "Neo-Neapolitan",
    hydration: 0.68,
    salt: 0.028,
    yeast: 0.0020,
    fermentationMin: 36,
    fermentationMax: 72,
    sauce: { tomatoType: "San Marzano", saltPercent: 0.006, oliveOilPercent: 0.010, basil: false, notesPerPizza: 100 },
    color: "#60A5FA",
    flourW: "W300–330",
    hydrationRange: "65–72%",
    saltRange: "2.5–3.0%",
    yeastRange: "0.1–0.3%",
    fermentationRange: "36–72 hrs",
    mixing: "Direct",
    characteristics: "Strong oven spring and open crumb",
    mainFocus: "Open crumb and modern fermentation techniques.",
    recipe1000g: { water: "680g", salt: "28g", yeast: "2g IDY" },
    fermentationApproach: "Long cold fermentation",
    bulkTime: "12–24 hrs",
    ballTime: "24–48 hrs",
    totalTime: "36–72 hrs",
    tempPreference: "Cold ferment",
    saucePreference: "Raw crushed tomatoes with salt",
    philosophy: "Open crumb and strong oven spring.",
    saucePhilosophy: "Raw tomatoes seasoned lightly to preserve freshness.",
    sauceRecipe1000g: { tomatoes: "1000g", salt: "10g", oliveOil: "Minimal", basil: "Optional", other: "None" },
    technique: {
      level: "Cornicione Protection Protocol",
      stretching: "Drop the dough ball cleanly into a bowl of dry semolina, lift onto the counter, then with flat fingers press down firmly from the center outward. Stop exactly 1 inch before the edge — never pinch, roll, or press the outer rim. This locks the delicate air pockets cleanly into a pristine cornicione.",
      notes: [
        { title: "Why It Matters", detail: "Touching the rim degasses it. By isolating pressure to the inner disc, the rim balloons in the oven into the dramatic, leopard-spotted cornicione Ayala is known for." },
      ],
      videos: [
        { category: "dough", title: "How to make pizza at home", url: "https://www.youtube.com/watch?v=4JaNGYMTviA" },
        { category: "stretching", title: "How to stretch Neapolitan pizza", url: "https://www.youtube.com/watch?v=yKbERrUrhXE" },
        { category: "recipe", title: "Restaurant pizzas", url: "https://www.youtube.com/watch?v=u8e9LYh6-Yo" },
        { category: "recipe", title: "Clandestine pizzas", url: "https://www.youtube.com/watch?v=vxQLt4ode2k&t=832s" },
      ],
    },
  },
  {
    id: "vito-iacopelli",
    name: "Vito Iacopelli",
    style: "Neo-Neapolitan / Home Pizza",
    hydration: 0.68,
    salt: 0.030,
    yeast: 0.0030,
    fermentationMin: 48,
    fermentationMax: 72,
    preferment: "poolish",
    sauce: { tomatoType: "San Marzano", saltPercent: 0.005, oliveOilPercent: 0.020, basil: true, notesPerPizza: 100 },
    color: "#F472B6",
    flourW: "W300–340",
    hydrationRange: "65–70%",
    saltRange: "2.8–3.0%",
    yeastRange: "Poolish + 2–5g IDY",
    fermentationRange: "48–72 hrs",
    mixing: "Poolish",
    characteristics: "Puffy crust, sweet fermentation notes",
    mainFocus: "Poolish-based doughs accessible to home pizza makers.",
    recipe1000g: { water: "680g", salt: "30g", yeast: "3g IDY in poolish" },
    fermentationApproach: "Poolish-based fermentation",
    bulkTime: "Poolish 16–24 hrs",
    ballTime: "24–48 hrs",
    totalTime: "48–72 hrs",
    tempPreference: "Cold + ambient",
    saucePreference: "Crushed tomatoes, salt, olive oil, occasional basil",
    philosophy: "Flavor development through preferments (poolish).",
    saucePhilosophy: "Slightly more home-cook friendly seasoning.",
    sauceRecipe1000g: { tomatoes: "1000g", salt: "10g", oliveOil: "10–15g", basil: "Yes", other: "Occasionally oregano" },
    technique: {
      level: "Authentic Neapolitan Slap Technique",
      stretching: "The traditional Neapolitan “slap” (schiaffo). Press the air out to the rim, then lift the left edge of the dough with the right hand, slap it down onto the floured counter, and flip it over the left hand in a fluid, continuous motion. This opens a highly hydrated, sticky dough instantly without tearing the delicate center.",
      notes: [
        { title: "Why It Works", detail: "The slap-and-flip releases the dough cleanly between hand and counter — friction stays low and the cornicione never gets pressed." },
      ],
      videos: [
        { category: "dough", title: "Next-level pizza dough (double fermented + poolish)", url: "https://www.youtube.com/watch?v=lj05Vje86uo&t=328s" },
        { category: "dough", title: "Flat pizza", url: "https://www.youtube.com/watch?v=SZflCxA1-a0" },
        { category: "hydration", title: "In-depth hydration", url: "https://www.youtube.com/watch?v=nu5iyLdEIjY" },
        { category: "stretching", title: "How to stretch a real pizza (slap technique)", url: "https://www.youtube.com/watch?v=h75bxDwT1Ko" },
        { category: "general", title: "Tips and tricks", url: "https://www.youtube.com/watch?v=NK2HQ0Il8BY" },
        { category: "general", title: "Tips for perfection", url: "https://www.youtube.com/watch?v=oqO4EVobmXc&t=554s" },
        { category: "general", title: "In-depth perfection", url: "https://www.youtube.com/watch?v=vEkkU6uXsHQ" },
        { category: "recipe", title: "My pizzas", url: "https://www.youtube.com/watch?v=rCb03Py2das" },
      ],
    },
  },
  {
    id: "marcpizza",
    name: "MarcPizza",
    style: "Neo-Neapolitan",
    hydration: 0.70,
    salt: 0.028,
    yeast: 0.0010,
    fermentationMin: 48,
    fermentationMax: 72,
    sauce: { tomatoType: "Mutti / San Marzano", saltPercent: 0.007, oliveOilPercent: 0.015, basil: true, notesPerPizza: 100 },
    color: "#A78BFA",
    flourW: "W300–330",
    hydrationRange: "68–72%",
    saltRange: "2.5–3.0%",
    yeastRange: "0.05–0.2%",
    fermentationRange: "24–72 hrs",
    mixing: "Direct/Biga",
    characteristics: "Open crumb with good handling",
    mainFocus: "Modern Neapolitan with strong fermentation focus.",
    recipe1000g: { water: "700g", salt: "28g", yeast: "1g IDY" },
    fermentationApproach: "Long cold ferment",
    bulkTime: "12–24 hrs",
    ballTime: "24–48 hrs",
    totalTime: "48–72 hrs",
    tempPreference: "Cold ferment",
    saucePreference: "Raw tomato sauce, lightly seasoned",
    philosophy: "Balancing extensibility and structure.",
    saucePhilosophy: "Minimal seasoning to highlight tomato quality.",
    sauceRecipe1000g: { tomatoes: "1000g", salt: "10g", oliveOil: "Minimal", basil: "Optional", other: "None" },
    technique: {
      level: "Long-Ferment Poolish Method",
      stretching: "A poolish-built dough is light and pillowy. Lightly flour the ball, press gently from the center outward, and let the natural extensibility from the preferment do most of the work — minimal handling preserves the bubbles.",
      notes: [
        { title: "Preferment First", detail: "Build a 100%-hydration poolish 16–24 hours ahead with a tiny pinch of yeast. The mature poolish drives flavor and extensibility before any kneading begins." },
        { title: "Patience", detail: "Long room-temp rests between mix, bulk and ball — rushing the rests will tighten the gluten and fight the open crumb." },
      ],
      videos: [
        { category: "dough", title: "48-hour fermentation pizza dough", url: "https://www.youtube.com/watch?v=676qnooL2tY" },
        { category: "dough", title: "Making pizza dough the easy way", url: "https://www.youtube.com/watch?v=LARqYnxCFCE" },
        { category: "dough", title: "How to make poolish", url: "https://www.youtube.com/watch?v=vXLZp8liBCo&t=4s" },
        { category: "general", title: "Making pizza", url: "https://www.youtube.com/watch?v=QbOULZRtuqM&t=62s" },
        { category: "dough", title: "Pizza dough with poolish", url: "https://www.youtube.com/watch?v=314aC_77us8" },
        { category: "stretching", title: "Crust / cheese border (cornicione)", url: "https://www.youtube.com/watch?v=t2VksIUTquc" },
        { category: "general", title: "How to make pizza end to end", url: "https://www.youtube.com/watch?v=oiDzYuKXcFk" },
        { category: "stretching", title: "Stretching the dough", url: "https://www.youtube.com/watch?v=SMZPfbfU2EM" },
        { category: "dough", title: "Making the dough balls", url: "https://www.youtube.com/watch?v=vVXvoQJKaMU" },
        { category: "stretching", title: "Stretching technique", url: "https://www.youtube.com/watch?v=psYoC_avA40" },
        { category: "stretching", title: "Stretching (short)", url: "https://www.youtube.com/shorts/RBs5uMlD9MI" },
        { category: "stretching", title: "Stretching with semolina", url: "https://www.youtube.com/watch?v=C45tsYjdONs" },
      ],
    },
  },
  {
    id: "salvatore-salvo",
    name: "Salvatore Salvo",
    style: "Traditional Neapolitan (Fratelli Salvo)",
    hydration: 0.65,
    salt: 0.028,
    yeast: 0.0010,
    fermentationMin: 36,
    fermentationMax: 60,
    sauce: { tomatoType: "San Marzano DOP", saltPercent: 0.004, oliveOilPercent: 0, basil: false, notesPerPizza: 90 },
    color: "#34D399",
    flourW: "W280–320",
    hydrationRange: "63–68%",
    saltRange: "2.7–3.0%",
    yeastRange: "0.05–0.15%",
    fermentationRange: "36–60 hrs",
    mixing: "Direct",
    characteristics: "Classic Neapolitan structure, soft and digestible",
    mainFocus: "Similar philosophy to Ciro, emphasizing softness and digestibility.",
    recipe1000g: { water: "650g", salt: "28g", yeast: "1g fresh yeast" },
    fermentationApproach: "Very long fermentation",
    bulkTime: "12–24 hrs",
    ballTime: "24–36 hrs",
    totalTime: "36–60 hrs",
    tempPreference: "Controlled temperature",
    saucePreference: "High-quality crushed tomatoes, minimal intervention",
    philosophy: "Softness, digestibility, and moisture retention.",
    saucePhilosophy: "Similar minimalist approach.",
    sauceRecipe1000g: { tomatoes: "1000g", salt: "8–10g", oliveOil: "None", basil: "Optional", other: "None" },
    technique: {
      level: "Fratelli Salvo Traditional Discipline",
      stretching: "Same traditional Neapolitan slap (schiaffo) lineage as Ciro, but on a drier dough (~65% hydration) that holds shape more readily. Press the gas to the rim, lift, slap and flip — controlled and unhurried.",
      notes: [
        { title: "Handling", detail: "The lower hydration is more forgiving to handle than Ciro's 73–75% — still avoid touching the rim to keep the cornicione airy." },
      ],
      videos: [
        { category: "general", title: "Salvatore Salvo — pizza video 1", url: "https://www.youtube.com/watch?v=D1R_eKkR7dI" },
        { category: "general", title: "Salvatore Salvo — pizza video 2", url: "https://www.youtube.com/watch?v=T4JCUS_jzSI" },
        { category: "general", title: "Salvatore Salvo — pizza video 3", url: "https://www.youtube.com/watch?v=MLWNjNxFTzk" },
      ],
    },
  },
  {
    id: "anthony-mangieri",
    name: "Anthony Mangieri",
    style: "Naturally-Leavened Neapolitan",
    hydration: 0.67,
    salt: 0.030,
    yeast: 0,
    fermentationMin: 24,
    fermentationMax: 48,
    preferment: "sourdough",
    sauce: { tomatoType: "Bianco DiNapoli", saltPercent: 0.008, oliveOilPercent: 0.010, basil: false, notesPerPizza: 110 },
    color: "#FBBF24",
    flourW: "W320–360",
    hydrationRange: "65–70%",
    saltRange: "2.8–3.2%",
    yeastRange: "100% sourdough starter",
    fermentationRange: "24–48 hrs",
    mixing: "Direct",
    characteristics: "Naturally leavened, deep flavor, soft center",
    mainFocus: "Ingredient quality and fermentation flavor over extreme hydration.",
    recipe1000g: { water: "670g", salt: "30g", yeast: "~350g 100% hydration sourdough starter (no commercial yeast)" },
    fermentationApproach: "Long maturation focused on flavor",
    bulkTime: "12–24 hrs",
    ballTime: "12–24 hrs",
    totalTime: "24–48 hrs",
    tempPreference: "Controlled ambient",
    saucePreference: "Raw premium tomatoes, salt only",
    philosophy: "Flavor first; fermentation as the primary ingredient.",
    saucePhilosophy: "Almost no manipulation of the tomatoes.",
    sauceRecipe1000g: { tomatoes: "1000g", salt: "8–10g", oliveOil: "None", basil: "No (typically added on pizza)", other: "None" },
    technique: {
      level: "Sourdough Purist Hand-Stretch",
      stretching: "A naturally leavened, structured dough that stretches cleanly with minimal motion. Flat fingers from the center outward on a lightly floured counter — confident, deliberate, and quick. The structure from the long sourdough maturation does most of the work.",
      notes: [
        { title: "Sauce", detail: "Sauce is barely a touch — use the back of a spoon to lightly distribute hand-crushed raw tomatoes with only a pinch of salt. No oil, no basil, no cooking." },
        { title: "Starter Discipline", detail: "Refresh the 100%-hydration starter 1:1:1 around 8–12 hours before mixing so it at least doubles before use — Mangieri's dough lives or dies on starter health." },
      ],
      videos: [
        { category: "dough", title: "Anthony Mangieri — pizza dough recipe", url: "https://www.youtube.com/watch?v=8-veXaCuJvg" },
        { category: "general", title: "Anthony Mangieri — pizza video", url: "https://www.youtube.com/watch?v=LFQZzbCtng0" },
      ],
    },
  },
];

export function getPizzaiolo(id: string): Pizzaiolo | undefined {
  return PIZZAIOLI.find((p) => p.id === id);
}
